#ifndef OLED_LEARNING_BUTTON_DETECTOR_H
#define OLED_LEARNING_BUTTON_DETECTOR_H

#define BUTTON_LEFT_PIN 18
#define BUTTON_CENTER_PIN 19
#define BUTTON_RIGHT_PIN 5

void setup_button_detector();

#endif //OLED_LEARNING_BUTTON_DETECTOR_H
